### ISSUE TITLE
Transaction hash is created by node but not visible in block explorer

### ISSUE THREAD

**Issue by yurayakimenko** [bnb-chain/bsc#1496]
#### System information

Version of BSC: v1.1.23 & v1.1.21
OS & Version: CentOS Linux release 7.9.2009 (Core)
CMD: `geth_bsc --config /bsc/config.toml --datadir /some_path/bsc --datadir.ancient /some_path/bnb20/ancient --cache 18000 --rpc.allow-unprotected-txs --txlookuplimit 0 --diffsync --txpool.reannouncetime 5m --syncmode snap`

#### Expected behavior
Transactions should appear in blockchain and block explorer after node gave hash.

#### Actual behavior

I got such entry in logs:
`t=2023-04-20T15:16:53+0300 lvl=info msg="Submitted transaction" hash= from= nonce=15100 recipient= value=108,345,000,000,000 x-forward-ip=nil`

I removed hash, from and recipient for privacy. But they are presented in real log.

But if I search for hash that node gave to me - it doesn't appear in blockchain.

On v1.1.21 I got several success transactions with regular BNB coins transfer and then this issue appears again when I try to send USDT token.

On v1.1.23 it doesn't work at all.

Before update to v1.1.23 everything was working fine.

#### Steps to reproduce the behavior

Try to send some BNB to address that has USDT on it using v1.1.23 or v1.1.21, than send some USDT from that address to another.

**Comment by banlieu451** [comment]
Pléase share your TX build code did your node me synced ? Try To add nonce ?

**Comment by jcchevalier-ledger** [comment]
Hello guys 👋 !
We are facing the same issue with our Binance node, it seems that some transactions are accepted then deleted from our txpool, before they could be mined.
Version: v1.1.23
config: `--syncmode full --txlookuplimit 0 -config some/config/file`
For instance a user tried to transfer [BUSD-T token](https://bscscan.com/token/0xe9e7cea3dedca5984780bafc599bd69add087d56) with decent gas (about 86k units) and gas price (5 Gwei). The node seemed to accept the transaction: we have the same log `msg="Submitted transaction"` with the sender, its nonce, the contract and the txHash. But somehow, the transaction just disappeared from the txpool. We broadcasted the exact same payload one day later and it worked.

**Comment by yurayakimenko** [comment]
For me issue was solved by starting blockchain sync from scratch. So possibly some of these versions (v1.1.21 or v1.1.22) are spoiling local blockchain data, be careful.

**Comment by zzzckck** [comment]
close now, could reopen if the latest v1.3.x releases still have the issue.

**Comment by nining** [comment]
> Hello guys 👋 !
> 
> We are facing the same issue with our Binance node, it seems that some transactions are accepted then deleted from our txpool, before they could be mined. Version: v1.1.23 config: `--syncmode full --txlookuplimit 0 -config some/config/file`
> 
> For instance a user tried to transfer [BUSD-T token](https://bscscan.com/token/0xe9e7cea3dedca5984780bafc599bd69add087d56) with decent gas (about 86k units) and gas price (5 Gwei). The node seemed to accept the transaction: we have the same log `msg="Submitted transaction"` with the sender, its nonce, the contract and the txHash. But somehow, the transaction just disappeared from the txpool. We broadcasted the exact same payload one day later and it worked.

I have the same issue. I occurred sometimes. I'm running version 1.4.6.
